from app.schemas.discovery import TopicEnum

CURATED_TOPIC_POOLS: dict[TopicEnum, list[str]] = {
    TopicEnum.SPACE: [
        "James_Webb_Space_Telescope", "Hubble_Space_Telescope", "Voyager_1", "Voyager_2",
        "Apollo_11", "International_Space_Station", "Curiosity_(rover)", "Perseverance_(rover)",
        "Cassini–Huygens", "New_Horizons", "Pillars_of_Creation", "Andromeda_Galaxy",
        "Milky_Way", "Supermassive_black_hole", "Event_Horizon_Telescope", "Neutron_star",
        "Pulsar", "Quasar", "Supernova", "Nebula",
        "Orion_Nebula", "Crab_Nebula", "Jupiter", "Saturn",
        "Mars", "Europa_(moon)", "Enceladus", "Titan_(moon)",
        "Ganymede_(moon)", "Kuiper_belt", "Oort_cloud", "Proxima_Centauri",
        "TRAPPIST-1", "Exoplanet", "Gravitational_wave", "LIGO",
        "Dark_matter", "Dark_energy", "Cosmic_microwave_background", "Big_Bang",
        "General_relativity", "Solar_flare", "Coronal_mass_ejection", "Asteroid_belt",
        "Ceres_(dwarf_planet)", "Pluto", "Halley's_Comet", "Comet_67P/Churyumov–Gerasimenko",
        "Parker_Solar_Probe", "Kepler_space_telescope", "Spitzer_Space_Telescope", "Chandra_X-ray_Observatory",
        "Betelgeuse", "Sirius", "Alpha_Centauri", "Voyager_Golden_Record",
        "Apollo_program", "Artemis_program", "Space_Shuttle", "Mir",
        "Sputnik_1", "Yuri_Gagarin", "Neil_Armstrong", "Carl_Sagan",
        "Stephen_Hawking", "Albert_Einstein", "Edwin_Hubble", "Johannes_Kepler",
        "Nicolaus_Copernicus", "Galileo_Galilei", "Fermi_paradox", "Drake_equation",
        "Kardashev_scale", "Dyson_sphere", "Space_elevator", "Interstellar_travel",
        "Solar_wind", "Van_Allen_radiation_belt", "Magnetosphere", "Aurora",
        "Black_hole", "White_dwarf", "Red_giant", "Planetary_nebula",
        "Gamma-ray_burst", "Cosmic_ray", "Cosmic_string", "Multiverse",
        "Observable_universe", "Cosmological_constant", "Hubble's_law", "Inflation_(cosmology)",
        "Stellar_nucleosynthesis", "Supercluster", "Laniakea_Supercluster", "Virgo_Supercluster",
        "Great_Attractor", "Boötes_void", "Dark_flow", "Heat_death_of_the_universe"
    ],
    TopicEnum.HISTORY: [
        "Library_of_Alexandria", "Colosseum", "Great_Pyramid_of_Giza", "Hanging_Gardens_of_Babylon",
        "Parthenon", "Roman_Empire", "Ancient_Greece", "Mesopotamia",
        "Silk_Road", "Byzantine_Empire", "Ottoman_Empire", "Renaissance",
        "Age_of_Discovery", "Industrial_Revolution", "French_Revolution", "American_Revolution",
        "World_War_I", "World_War_II", "Cold_War", "Space_Race",
        "Magna_Carta", "Code_of_Hammurabi", "Rosetta_Stone", "Dead_Sea_Scrolls",
        "Pompeii", "Machu_Picchu", "Angkor_Wat", "Petra",
        "Chichen_Itza", "Taj_Mahal", "Great_Wall_of_China", "Terracotta_Army",
        "Mohenjo-daro", "Hagia_Sophia", "Viking_Age", "Black_Death",
        "Printing_press", "Age_of_Enlightenment", "Protestant_Reformation", "Scientific_Revolution",
        "Julius_Caesar", "Alexander_the_Great", "Cleopatra", "Leonardo_da_Vinci",
        "Michelangelo", "Isaac_Newton", "Marie_Curie", "Charles_Darwin",
        "Nelson_Mandela", "Mahatma_Gandhi", "Martin_Luther_King_Jr.", "Winston_Churchill",
        "Fall_of_the_Western_Roman_Empire", "Fall_of_Constantinople", "Treaty_of_Versailles", "Berlin_Wall",
        "Cuban_Missile_Crisis", "Apollo_11", "Manhattan_Project", "Suez_Crisis",
        "Battle_of_Waterloo", "Battle_of_Hastings", "Battle_of_Stalingrad", "Battle_of_Midway",
        "Voyages_of_Christopher_Columbus", "Ferdinand_Magellan", "Marco_Polo", "Ibn_Battuta",
        "Sumer", "Ancient_Egypt", "Indus_Valley_Civilisation", "Maya_civilization",
        "Inca_Empire", "Aztec_Empire", "Mongol_Empire", "British_Empire",
        "Pax_Romana", "Gutenberg_Bible", "Declaration_of_Independence_(United_States)", "Universal_Declaration_of_Human_Rights",
        "Sinking_of_the_Titanic", "Chernobyl_disaster", "Spanish_flu", "Enigma_machine",
        "Turing_machine", "Marshall_Plan", "League_of_Nations", "United_Nations",
        "Hanseatic_League", "Gold_Rush", "Panama_Canal", "Transcontinental_railroad"
    ],
    TopicEnum.BIOLOGY: [
        "Photosynthesis", "DNA", "RNA", "CRISPR",
        "Mitochondrion", "Cell_membrane", "Ribosome", "Endoplasmic_reticulum",
        "Cellular_respiration", "Mitosis", "Meiosis", "Epigenetics",
        "Evolution", "Natural_selection", "Speciation", "Adaptation",
        "Human_genome", "Neanderthal", "Australopithecus", "Origin_of_life",
        "Abiogenesis", "Endosymbiotic_theory", "Cambrian_explosion", "Mass_extinction_event",
        "Cretaceous–Paleogene_extinction_event", "Tardigrade", "Immortal_jellyfish", "Axolotl",
        "Octopus", "Platypus", "Blue_whale", "Great_white_shark",
        "Peregrine_falcon", "Monarch_butterfly", "Honey_bee", "Mycorrhiza",
        "Bioluminescence", "Circadian_rhythm", "Neuroplasticity", "Synapse",
        "Action_potential", "Central_nervous_system", "Immune_system", "Antibody",
        "T_cell", "Macrophage", "Vaccine", "Antimicrobial_resistance",
        "Gut_microbiota", "Bacteriophage", "Virus", "Prion",
        "Stem_cell", "Telomere", "Apoptosis", "Gene_expression",
        "Mendelian_inheritance", "Chromatophore", "Echolocation", "Chemosynthesis",
        "Hydrothermal_vent", "Coral_reef", "Great_Barrier_Reef", "Amazon_rainforest",
        "Tundra", "Taiga", "Mangrove", "Symbiosis",
        "Mutualism_(biology)", "Parasitism", "Commensalism", "Trophic_level",
        "Keystone_species", "Apex_predator", "Biomimicry", "Synthetic_biology",
        "Cloning", "Dolly_(sheep)", "Human_Microbiome_Project", "Chlamydia",
        "Chloroplast", "ATP_synthase", "Enzyme", "Hemoglobin",
        "Cephalopod_intelligence", "Crow_intelligence", "Chimpanzee", "Jane_Goodall",
        "Gregor_Mendel", "Alexander_Fleming", "Louis_Pasteur", "Rosalind_Franklin"
    ],
    TopicEnum.TECH: [
        "Artificial_intelligence", "Machine_learning", "Deep_learning", "Neural_network",
        "Transformer_(deep_learning_architecture)", "Large_language_model", "Computer_vision", "Natural_language_processing",
        "Quantum_computing", "Qubit", "Quantum_supremacy", "Cryptography",
        "Public-key_cryptography", "RSA_(cryptosystem)", "Blockchain", "Bitcoin",
        "Internet", "World_Wide_Web", "ARPANET", "Transmission_Control_Protocol",
        "Internet_Protocol", "Domain_Name_System", "Cloud_computing", "Virtualization",
        "Operating_system", "Linux", "Unix", "Kernel_(operating_system)",
        "Microprocessor", "Transistor", "Moore's_law", "Integrated_circuit",
        "Semiconductor", "Photolithography", "GPU", "Central_processing_unit",
        "Quantum_dot", "OLED", "Fiber-optic_communication", "5G",
        "Wi-Fi", "Bluetooth", "Satellite_internet_constellation", "Starlink",
        "Autonomous_vehicle", "Lidar", "Computer-aided_design", "3D_printing",
        "Robotics", "Boston_Dynamics", "Humanoid_robot", "Brain–computer_interface",
        "Neuralink", "Nanotechnology", "Graphene", "Carbon_nanotube",
        "Nuclear_fusion", "Tokamak", "ITER", "Solar_cell",
        "Lithium-ion_battery", "Solid-state_battery", "Electric_vehicle", "Supercapacitor",
        "Supercomputer", "Distributed_computing", "Kubernetes", "Docker_(software)",
        "Relational_database", "NoSQL", "Graph_database", "Compiler",
        "Turing_machine", "Alan_Turing", "John_von_Neumann", "Claude_Shannon",
        "Tim_Berners-Lee", "Grace_Hopper", "Ada_Lovelace", "Dennis_Ritchie",
        "Linus_Torvalds", "Steve_Jobs", "Silicon_Valley", "Bell_Labs",
        "Xerox_PARC", "Computer_graphics", "Ray_tracing_(graphics)", "Augmented_reality",
        "Virtual_reality", "Optical_computing", "Memristor", "Edge_computing"
    ]
}
